import React from "react";
import logo from "../public/images/logos/kenken.svg";
import nextLogo from "../public/images/logos/cards.svg";
import WorkPage from "../components/WorkPage";
import uml from "../public/images/kenken/uml.svg";

function EsRecader() {
  const work = {
    title: "Ken Ken",
    subtitle: "Desktop App to play KenKens",
    logo: logo,
    video: "ken-ken-compressed",
    images: {
      uml: uml,
    },
  };

  const texts = {
    overview: `This is a very complete desktop app designed for people to play KenKens. A KenKen is a puzzle similar to a Sudoku with the extra step of restrictions based on operations as addition, substraction or multiplication among others With this app you can play, propose, generate, import, export KenKens and load and save games. 
    `,
    role: "Design & Development",
    page: "https://github.com/Blondie-TheManWithNoName/ken-ken",
    pageText: "GitHub Repository",
    why: `The user is able to play a random KenKen generated by the program, a proposed KenKen proposed by the user from scratch, a generated one by chosing the restrictions and shapes or an imported one from a file. This includes an export KenKen files,`,
  };

  const pills = [
    "Java",
    "Swing",
    "Unit Test",
    "MVC Pattern",
    "IntelliJ",
    "UML",
    "Figma",
    "Trello",
    "Git",
  ];

  const nextWork = {
    url: "cardmat",
    logo: nextLogo,
    title: "Card Mat",
  };
  return (
    <WorkPage
      work={work}
      texts={texts}
      nextWork={nextWork}
      pills={pills}
    ></WorkPage>
  );
}

export default EsRecader;
